### ISSUE TITLE
The function named Switch in import_sstpb.proto will be named as switch when generating java code

### ISSUE THREAD

**Issue by mopishv0** [pingcap/kvproto#272]
The function named Switch in import_sstpb.proto will be named as switch when generating java code.
It make an error when i compile tispark/tikv-client:

[ERROR] /tispark/tikv-client/target/generated-sources/protobuf/grpc-java/com/pingcap/tikv/kvproto/ImportSSTGrpc.java:[141,16] <identifier> expected

**Comment by birdstorm** [comment]
Hi, @mopishv0.

Thanks for your feedback, before this function is renamed, you might need to modify `tikv-client/scripts/proto.sh:18` to `cd kvproto; git checkout b7ba8ea1c0b4915d333a146eb0e674fb5b33854f; cd ..` in order to build TiSpark successfully. 

We will inform you as soon as the problem is fixed. PTAL @huachaohuang
